# Generated by Django 3.1.4 on 2021-01-13 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CCITUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uID', models.CharField(max_length=11, unique=True, verbose_name='用户ID')),
                ('upwd', models.CharField(max_length=18, verbose_name='密码')),
                ('uname', models.CharField(max_length=128, verbose_name='姓名')),
                ('uregistertime', models.DateTimeField(auto_now_add=True, verbose_name='注册时间')),
                ('uemail', models.CharField(max_length=128, verbose_name='邮箱')),
                ('ustatus', models.CharField(max_length=1, verbose_name='用户状态')),
            ],
        ),
    ]
