# Generated by Django 3.1.4 on 2021-01-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ccituser',
            options={'ordering': ['uID'], 'verbose_name': '班级管理员', 'verbose_name_plural': '班级管理员s'},
        ),
        migrations.AlterModelTable(
            name='ccituser',
            table='class_table',
        ),
    ]
